---
- name: Launch EC2 instance with New Relic Integration
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # EC2 Configuration
    default_instance_prefix: "EC2-NewRelic"
    region: ap-south-1
    ami_id: ami-0a1235697f4afa8a4            # Amazon Linux 2023 AMI (ap-south-1)
    instance_type: t2.nano                   # 1vCPU 0.5 GiB Memory
    key_name: AL2023                         # Replace with your key pair name
    subnet_id: subnet-0b9b0f798dbe19be2      # Replace with your subnet ID
    security_group: sg-0703680985f56f283     # Replace with your security group ID

    # New Relic Variables (pass API key and account  ID)
    NEW_RELIC_API_KEY: "NRAK-04XUDJPPZ4BV0CVSJXEUV4ZTWWX" # API Key type as User 
    NEW_RELIC_ACCOUNT_ID: "6978270"  # Account ID

  tasks:
    - name: ðŸ§® Generate random suffix (only once)
      set_fact:
        generated_suffix: "{{ 99999 | random }}"

    - name: ðŸ·ï¸ Set final EC2 instance name
      set_fact:
        instance_name_final: "{{ instance_name | default(default_instance_prefix ~ '-' ~ generated_suffix) }}"

    - name: ðŸ“œ Create EC2 user_data script with New Relic install
      set_fact:
        ec2_user_data: |
          #!/bin/bash
          sudo yum update -y
          sudo curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash
          sudo NEW_RELIC_API_KEY={{ NEW_RELIC_API_KEY }} NEW_RELIC_ACCOUNT_ID={{ NEW_RELIC_ACCOUNT_ID }} /usr/local/bin/newrelic install -y
          sudo sh -c "echo 'display_name: Ec2-AL2023-$(date +%Y%m%d)' >> /etc/newrelic-infra.yml"
          sudo systemctl restart newrelic-infra.service

    - name: ðŸš€ Launch EC2 instance with New Relic user_data
      amazon.aws.ec2_instance:
        name: "{{ instance_name_final }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        wait: yes
        count: 1
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet_id }}"
        security_group: "{{ security_group }}"
        tags:
          Name: "{{ instance_name_final }}"
        user_data: "{{ ec2_user_data }}"
      register: ec2_result

    - name: ðŸ“‹ Show instance details
      debug:
        msg:
          - "âœ… EC2 Deployed Successfully with NewRelic Integration:"
          - "  - Instance Name: {{ instance_name_final }}"
          - "  - Instance ID: {{ ec2_result.instance_ids[0] }}"
          - "  - Public IP: {{ ec2_result.instances[0].public_ip_address }}"
