---
- name: Run Docker Container from Docker Image
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    docker_image_name: al-nginx-newrelic-image
    docker_image_tag: latest
    docker_container_name: al-nginx-newrelic-conatiner
    docker_ports: "80:80"
  
  tasks:
    - name: 🚀 Run Docker container
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image_name }}:{{ docker_image_tag }}"
        recreate: yes       # Recreate container if image tag changed
        state: started
        ports: "{{ docker_ports }}"
        restart_policy: always
      register: run_result

    - name: 🪵 Debug Run Result
      debug:
        var: run_result
